---
- hosts: all
  become: yes
  tasks:
  - name: update
    package:
      name: "{{ updation }}"
      update_cache: yes
  - name: install
    package:
      name: "{{ server }}"
      state: present
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
     - php
     - php-mysql
    notify:
    - restart server
  handlers:
  - name: restart server
    service:
      name: server
      state: restarted

